title: Houdini snippets
description: A collection of VEX and Python snippets for use in Houdini. This repository is maintained by Robbert Groenendijk.
show_downloads: true
remote_theme: lewismiddleton/cayman-dark

