title: Houdini Snippets
description: A collection of Houdini snippets in VEX, Python, HDA and .hip files.
show_downloads: true
remote_theme: pmarsceill/just-the-docs
color_scheme: customscheme


aux_links:
  "View on GitHub":
    - "//github.com/RobbertGroenendijk/Houdini_snippets"


back_to_top: true
back_to_top_text: "Back to top"

