title: Houdini Snippets
description: A collection of Houdini snippets in VEX, Python, HDA and .hip files.
baseurl: "/houdinisnippets"
url: "https://robbertgroenendijk.github.io"
show_downloads: true
remote_theme: pmarsceill/just-the-docs
color_scheme: dark

back_to_top: true
back_to_top_text: "Back to top"


